name: DIBenchmarkiOS
options:
  bundleIdPrefix: com.codeint.benchmarking
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "16.0"

settings:
  base:
    SWIFT_VERSION: "5.9"

targets:
  iosApp:
    type: application
    platform: iOS
    sources:
      - path: iosApp
        type: group
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.codeint.benchmarking.ios
        INFOPLIST_GENERATION: true
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        FRAMEWORK_SEARCH_PATHS:
          - "$(inherited)"
          - "../benchmark-kmp-metro/build/XCFrameworks/release/BenchmarkMetro.xcframework"
          - "../benchmark-kmp-koin/build/XCFrameworks/release/BenchmarkKoin.xcframework"
    dependencies:
      - framework: "../benchmark-kmp-metro/build/XCFrameworks/release/BenchmarkMetro.xcframework"
        embed: true
      - framework: "../benchmark-kmp-koin/build/XCFrameworks/release/BenchmarkKoin.xcframework"
        embed: true
